### ISSUE TITLE
Assets fail to load in the Vite dev server after updating to version 2.0.0

### ISSUE THREAD

**Issue by inkfarer** [nodecg/vite-plugin-nodecg#12]
I've noticed that non-code assets (such as images) have begun failing to load when using the Vite dev server after upgrading from version 2.0.0-rc3.

A minimal reproduction is available here: [Link](https://github.com/inkfarer/vite-nodecg-asset-loading-repro)

When using version 2.0.0-rc3, images are loaded from the Vite dev server, as expected:
<img width="718" alt="Screenshot 2024-03-02 at 01 04 28" src="https://github.com/nodecg/vite-plugin-nodecg/assets/6833028/09507efd-d485-443e-8bc1-8c3a0f33f7b0">
<img width="475" alt="Screenshot 2024-03-02 at 00 42 52" src="https://github.com/nodecg/vite-plugin-nodecg/assets/6833028/5ae0ace2-971c-40f2-a2de-30269419103f">

After upgrading the above repository to version 2.0.0, the bundle starts attempting to load images from the NodeCG server, which fails with a 404 error:
<img width="729" alt="Screenshot 2024-03-02 at 01 04 59" src="https://github.com/nodecg/vite-plugin-nodecg/assets/6833028/a94bf097-5412-46a7-9277-e466a2c678c1">
<img width="476" alt="Screenshot 2024-03-02 at 00 42 22" src="https://github.com/nodecg/vite-plugin-nodecg/assets/6833028/660be151-7b65-417f-85e0-215ebd4f5f61">

**Comment by EwanLyon** [comment]
Until my PR is merged and a new package uploaded a workaround is to mount the "src" folder in nodecg.

your-bundle/package.json
```json
{
  "nodecg": {
    "mount": [
      {
        "directory": "src",
        "endpoint": "src"
      }
    ]
  }
}
