### ISSUE TITLE
Entry Points in Subfolders Writes HTML Files to Wrong Location

### ISSUE THREAD

**Issue by grantjbutler** [nodecg/vite-plugin-nodecg#5]
If I set up my plugin config such that the entry points are within a subfolder where the folder name is the panel name, the plugin tries to write the resolved template file to the wrong location.

Given the following config:

```js
NodeCGPlugin({
  inputs: {
    './src/graphics/*/app.{js,ts}': './src/graphics/template.html',
    './src/dashboard/*/app.{js,ts}': './src/dashboard/template.html',
  }
})
```

and a folder structure like this:

```
my-nodecg-bundle/
├─ src/
│  ├─ dashboard/
│  │  ├─ uptime-timer/
│  │  │  ├─ app.ts
```

The plugin will try to write the template to `/my-nodecg-bundle/uptime-timer/app.html` and fail, as the folder `uptime-timer` doesn't exist. I would expect it to instead try to write the template to `/my-nodecg-bundle/dashboard/uptime-timer/app.html` (though I would ideally want the plugin to realize that it's writing to a subfolder within `dashboard/` and would thus name the file `index.html` instead).

**Comment by Dan-Shields** [comment]
This should be fixed in the latest prerelease. Please try it @grantjbutler and let me know. Sorry for the wait! 

It should write to /my-nodecg-bundle/dashboard/uptime-timer/app.html, though I'm not sure how to handle the dashboard subfolder thing. What's the motivation there?
