### ISSUE TITLE
Plugin Creates `dashboard` or `graphics` Directory When Not Specified

### ISSUE THREAD

**Issue by grantjbutler** [nodecg/vite-plugin-nodecg#6]
Given the following config:

```
NodeCGPlugin({
  inputs: {
    './src/dashboard/*.{js,ts}': './src/dashboard/template.html',
  }
})
```

and a directory structure like this:

```
my-nodecg-bundle/
├─ src/
│  ├─ dashboard/
│  │  ├─ app.ts
```

The plugin will create a `/my-nodecg-bundle/dashboard` folder (as expected), but also generates a `/my-nodecg-bundle/graphics` folder, even though I've not specified an input for graphics, nor does a `/my-nodecg-bundle/src/grahpics` folder exist. This in turn causes NodeCG to print an error and exit:

> Error: my-nodecg-bundle has a "graphics" folder, but no "nodecg.graphics" property was found in its package.json

I would expect this plugin to not generate directories when a corresponding input is absent (that is, for the given config and directory structure above, I would expect no `/my-nodecg-bundle/graphics/` folder to be created).

**Comment by Tempystral** [comment]
I'm experiencing a similar problem but I'm commenting on this ticket because the root issue is the same: I've found that not having a `src/dashboard` directory makes `build:browser` fail.
I'm similarly using
```
NodeCGPlugin( {
      inputs: { './src/graphics/*.{js,ts}': './src/graphics/template.html', }
    } )
```
with a directory like so:
```
my-nodecg-bundle/
├─ src/
│  ├─ graphics/
│  │  ├─ app.ts
```
And I get a build failure:
```
error during build:
Error: ENOENT: no such file or directory, open '/home/azurite/git/licenseathon-vue/src/dashboard/template.html'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at viteNodeCGPlugin (file:///home/azurite/git/licenseathon-vue/node_modules/vite-plugin-nodecg/dist/index.js:7:32)
```

**Comment by drB-dotjpg** [comment]
Having the same issue but with dashboard items.
My program doesn't have any dashboard items, only graphics. Upon building it'll still make a dashboard folder, and nodecg will throw an error if there's a dashboard folder with no dashboard items defined in `package.json` (for some reason)

**Comment by Dan-Shields** [comment]
Fixed in the prerelease, please try it (`pnpm i -D vite-plugin-nodecg@prerelease`) and let me know how you get on. (note the config change, detailed in the README)

**Comment by Tempystral** [comment]
Works great! I do think it is a tad awkward to have `srcDir` apply to the code inputs but not the template inputs? But it is now building the app with one or both or neither directories as expected. Thanks!

**Comment by Dan-Shields** [comment]
> I do think it is a tad awkward to have `srcDir` apply to the code inputs but not the template inputs?

I left it this way because you might want to have templates stored outside of the source directory.

The srcDir serves the specific purpose of being the base path for any input files found inside, such that the input's path relative to it is reflected in the output directory of the .html file, e.g. the input `bundle-dir/src/graphics/graphic1.js` has an html file output to `bundle-dir/graphics/graphic1.js`. 

I'm gonna update the README to explain this.

**Comment by Tempystral** [comment]
Makes sense, I thought it may be something like that. Stands to reason.
